import type { LookupType, ToolDefinition, ToolHealth } from "@/lib/types";
import { commandExists } from "@/lib/safeExec";

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: "osint_industries",
    repo: "external_api",
    category: "framework",
    enabledEnv: "ENABLE_OSINT_INDUSTRIES",
    defaultEnabled: false,
    riskLevel: "medium",
    priority: 10,
    commandName: null,
    installHint: "Create an OSINT Industries account, set OSINT_INDUSTRIES_API_KEY, then enable explicitly.",
    allowedTypes: ["email", "phone", "username", "name", "wallet"],
    notes: "API principale si clé disponible.",
    directProvider: true,
  },
  {
    id: "whatsmyname",
    repo: "WebBreacher/WhatsMyName",
    category: "username",
    enabledEnv: "ENABLE_WHATSMYNAME",
    defaultEnabled: true,
    riskLevel: "low",
    priority: 20,
    commandName: null,
    installHint: "Download the WhatsMyName web_accounts_list.json dataset manually into data/whatsmyname.json.",
    allowedTypes: ["username"],
    notes: "Dataset JSON, bon pour construire un moteur username sans lancer de scraping lourd.",
    directProvider: true,
  },
  {
    id: "socialscan",
    repo: "iojw/socialscan",
    category: "email",
    enabledEnv: "ENABLE_SOCIALSCAN",
    defaultEnabled: false,
    riskLevel: "medium",
    priority: 30,
    commandName: "socialscan",
    installHint: "pipx install socialscan",
    allowedTypes: ["email", "username"],
    notes: "Vérifie email/username sur certaines plateformes, limiter et désactiver par défaut.",
    directProvider: true,
  },
  {
    id: "sherlock",
    repo: "sherlock-project/sherlock",
    category: "username",
    enabledEnv: "ENABLE_SHERLOCK",
    defaultEnabled: false,
    riskLevel: "low",
    priority: 40,
    commandName: "sherlock",
    installHint: "pipx install sherlock-project",
    allowedTypes: ["username"],
    notes: "Recherche username sur de nombreux sites publics.",
    directProvider: true,
  },
  {
    id: "maigret",
    repo: "soxoj/maigret",
    category: "username",
    enabledEnv: "ENABLE_MAIGRET",
    defaultEnabled: false,
    riskLevel: "low",
    priority: 50,
    commandName: "maigret",
    installHint: "pipx install maigret",
    allowedTypes: ["username"],
    notes: "Dossier OSINT à partir d'un username.",
    directProvider: true,
  },
  {
    id: "blackbird",
    repo: "p1ngul1n0/blackbird",
    category: "email",
    enabledEnv: "ENABLE_BLACKBIRD",
    defaultEnabled: false,
    riskLevel: "medium",
    priority: 60,
    commandName: "blackbird",
    installHint: "Install from the official repository; keep exports local and filtered.",
    allowedTypes: ["email", "username"],
    notes: "Outil puissant username/email, exports possibles, limiter les résultats.",
    directProvider: true,
  },
  {
    id: "holehe",
    repo: "megadose/holehe",
    category: "email",
    enabledEnv: "ENABLE_HOLEHE",
    defaultEnabled: false,
    riskLevel: "high",
    priority: 70,
    commandName: "holehe",
    installHint: "pipx install holehe",
    allowedTypes: ["email"],
    notes: "Sensible. À utiliser uniquement en self-check/consent. Désactivé par défaut.",
    directProvider: true,
  },
  {
    id: "h8mail",
    repo: "khast3x/h8mail",
    category: "email",
    enabledEnv: "ENABLE_H8MAIL",
    defaultEnabled: false,
    riskLevel: "high",
    priority: 80,
    commandName: "h8mail",
    installHint: "pipx install h8mail",
    allowedTypes: ["email"],
    notes: "Breach hunting. Ne jamais afficher de mots de passe. Seulement metadata safe.",
    directProvider: true,
  },
  {
    id: "ghunt",
    repo: "mxrch/GHunt",
    category: "email",
    enabledEnv: "ENABLE_GHUNT",
    defaultEnabled: false,
    riskLevel: "high",
    priority: 90,
    commandName: "ghunt",
    installHint: "Follow the official GHunt installation and consent requirements.",
    allowedTypes: ["email"],
    notes: "Google/Gmail OSINT. Ne pas automatiser sur des tiers. Désactivé par défaut.",
    directProvider: true,
  },
  {
    id: "phoneinfoga",
    repo: "sundowndev/phoneinfoga",
    category: "phone",
    enabledEnv: "ENABLE_PHONEINFOGA",
    defaultEnabled: false,
    riskLevel: "medium",
    priority: 100,
    commandName: "phoneinfoga",
    installHint: "Install from the official PhoneInfoga release or documentation.",
    allowedTypes: ["phone"],
    notes: "Infos techniques téléphone, pays, format, pistes publiques. Ne pas prétendre trouver l'identité civile.",
    directProvider: true,
  },
  {
    id: "ignorant",
    repo: "megadose/ignorant",
    category: "phone",
    enabledEnv: "ENABLE_IGNORANT",
    defaultEnabled: false,
    riskLevel: "high",
    priority: 110,
    commandName: "ignorant",
    installHint: "pipx install ignorant",
    allowedTypes: ["phone"],
    notes: "Sensible. Vérifie association téléphone/services. Seulement self-check/consent. Désactivé par défaut.",
    directProvider: true,
  },
  {
    id: "snoop",
    repo: "snooppr/snoop",
    category: "username",
    enabledEnv: "ENABLE_SNOOP",
    defaultEnabled: false,
    riskLevel: "low",
    priority: 120,
    commandName: "snoop",
    installHint: "Install from the official Snoop repository.",
    allowedTypes: ["username"],
    notes: "Alternative username checker.",
    directProvider: true,
  },
  {
    id: "userrecon",
    repo: "vijaysahuofficial/UserReCon",
    category: "username",
    enabledEnv: "ENABLE_USERRECON",
    defaultEnabled: false,
    riskLevel: "medium",
    priority: 130,
    commandName: "userrecon",
    installHint: "Install from the official repository if you need legacy comparison.",
    allowedTypes: ["username"],
    notes: "Ancien outil username, qualité à benchmarker avant usage.",
    directProvider: true,
  },
  {
    id: "osint_namecheckers_list",
    repo: "soxoj/osint-namecheckers-list",
    category: "username",
    enabledEnv: "ENABLE_OSINT_NAMECHECKERS_LIST",
    defaultEnabled: false,
    riskLevel: "low",
    priority: 140,
    commandName: null,
    installHint: "Use as a reference list, not as an executable provider.",
    allowedTypes: ["username"],
    notes: "Liste comparative utile pour enrichir le benchmark, pas forcément provider direct.",
    directProvider: false,
  },
  {
    id: "spiderfoot",
    repo: "smicallef/spiderfoot",
    category: "framework",
    enabledEnv: "ENABLE_SPIDERFOOT",
    defaultEnabled: false,
    riskLevel: "medium",
    priority: 150,
    commandName: "spiderfoot",
    installHint: "Install and run separately using the official SpiderFoot documentation.",
    allowedTypes: ["email", "phone", "username", "name"],
    notes: "Framework OSINT large. À intégrer en mode optionnel, pas dans le flow rapide.",
    directProvider: true,
  },
  {
    id: "reconng",
    repo: "lanmaster53/recon-ng",
    category: "framework",
    enabledEnv: "ENABLE_RECONNG",
    defaultEnabled: false,
    riskLevel: "medium",
    priority: 160,
    commandName: "recon-ng",
    installHint: "Install and run separately using the official Recon-ng documentation.",
    allowedTypes: ["email", "username", "name"],
    notes: "Framework reconnaissance. Optionnel, probablement trop lourd pour MVP.",
    directProvider: true,
  },
  {
    id: "osint_framework",
    repo: "lockfale/osint-framework",
    category: "framework",
    enabledEnv: "ENABLE_OSINT_FRAMEWORK",
    defaultEnabled: false,
    riskLevel: "low",
    priority: 170,
    commandName: null,
    installHint: "Reference only.",
    allowedTypes: ["email", "phone", "username", "name", "wallet"],
    notes: "Ressource de mapping d'outils, pas à exécuter comme provider.",
    directProvider: false,
  },
  {
    id: "apis_for_osint",
    repo: "cipher387/API-s-for-OSINT",
    category: "framework",
    enabledEnv: "ENABLE_APIS_FOR_OSINT",
    defaultEnabled: false,
    riskLevel: "low",
    priority: 180,
    commandName: null,
    installHint: "Reference only.",
    allowedTypes: ["email", "phone", "username", "name", "wallet"],
    notes: "Liste d'APIs, utile dans README/POWERPOINT_NOTES.",
    directProvider: false,
  },
  {
    id: "telephone_osint",
    repo: "The-Osint-Toolbox/Telephone-OSINT",
    category: "phone",
    enabledEnv: "ENABLE_TELEPHONE_OSINT",
    defaultEnabled: false,
    riskLevel: "low",
    priority: 190,
    commandName: null,
    installHint: "Reference only.",
    allowedTypes: ["phone"],
    notes: "Ressource documentaire pour benchmark téléphone.",
    directProvider: false,
  },
];

export function getToolsForType(type: LookupType): ToolDefinition[] {
  return TOOL_REGISTRY.filter((tool) => tool.allowedTypes.includes(type)).sort((a, b) => a.priority - b.priority);
}

export function isToolEnabled(tool: ToolDefinition): boolean {
  const rawValue = process.env[tool.enabledEnv];
  if (rawValue === undefined || rawValue === "") {
    return tool.defaultEnabled;
  }
  return rawValue.toLowerCase() === "true";
}

export function isMockMode(): boolean {
  return (process.env.MOCK_MODE ?? "true").toLowerCase() !== "false";
}

export function providerTimeoutMs(defaultSeconds = 35): number {
  const seconds = Number.parseInt(process.env.PROVIDER_TIMEOUT_SECONDS ?? String(defaultSeconds), 10);
  return Math.max(1, seconds) * 1000;
}

export function maxSignalsPerProvider(): number {
  const value = Number.parseInt(process.env.MAX_SIGNALS_PER_PROVIDER ?? "25", 10);
  return Math.max(1, value);
}

export async function buildToolHealth(): Promise<ToolHealth[]> {
  return Promise.all(
    TOOL_REGISTRY.map(async (tool) => ({
      id: tool.id,
      repo: tool.repo,
      installed: tool.commandName ? await commandExists(tool.commandName) : tool.id === "osint_industries" ? Boolean(process.env.OSINT_INDUSTRIES_API_KEY) : false,
      enabled: isToolEnabled(tool),
      riskLevel: tool.riskLevel,
      supportedTypes: tool.allowedTypes,
      installHint: tool.installHint,
      notes: tool.notes,
    })),
  );
}
